<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'empty' => 'Пуста',
    'label_sc_link' => 'Спасылка на старонку Soundcloud',
    'label_sc_playlist' => 'Убудаваны плэйліст Soundcloud',
    'label_youtube_link' => 'Спасылка на канал Youtube',
    'label_youtube_video' => 'Убудаванае відэа Youtube',
    'more_music' => 'Больш музыкі',
    'more_video' => 'Больш відэа',
    'name' => 'Медыя',
    'with_link' => 'са спасылкаю',
];
