<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2019-01-01 10:37:58
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [],
        'css' => [
            'css/all-d7458e0e8a83cee549191dbd6e19dea7.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'css' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'yii\\web\\JqueryAsset',
    ],
    'app\\assets\\TempAsset' => [
        'css' => [
            '//fonts.googleapis.com/css?family=Roboto:100,300,400',
            '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css',
            '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
        ],
        'js' => [
            '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js',
        ],
        'sourcePath' => null,
        'basePath' => null,
        'baseUrl' => null,
        'depends' => [],
        'jsOptions' => [],
        'cssOptions' => [],
        'publishOptions' => [],
        'class' => 'app\\assets\\TempAsset',
    ],
    'app\\assets\\ResourcesAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'app\\assets\\TempAsset',
            'all',
        ],
    ],
];